# Generated by Django 4.0.4 on 2022-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=255)),
                ('qulification', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
